// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AnalyzeRequest struct {
	JobDescription string `json:"jobDescription"`
	Question       string `json:"question"`
}

type CommonResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
	Success bool        `json:"success"`
}
